release:
  name_template: "{{ .ProjectName }} v{{ .Version }}"

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/alertmanager_bot
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - format: binary
    name_template: '{{ .Binary }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/sputnik-systems/{{ .ProjectName }}:latest"
      - "ghcr.io/sputnik-systems/{{ .ProjectName }}:{{ .Tag }}"
    extra_files:
      - templates

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
