FROM golang:1.16.0-buster as build

RUN apt update \
    && apt install -y curl patch

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

RUN curl -s -L -o ./kubectl https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl \
    && chmod +x ./kubectl

COPY . .
RUN go build -o ./alertmanager_bot ./cmd/bot
RUN go build -o ./alertmanager_config_updater ./cmd/alertmanager_config_updater


FROM ubuntu

RUN apt-get update \
    && apt-get install -y ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=build /app/kubectl /usr/local/bin/
COPY --from=build /app/alertmanager_bot /usr/local/bin/
COPY --from=build /app/alertmanager_config_updater /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/alertmanager_bot"]
