/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package kubernetes

import (
	"fmt"

	// discovery "k8s.io/client-go/discovery"
	// admissionregistrationv1 "k8s.io/client-go/kubernetes/typed/admissionregistration/v1"
	// admissionregistrationv1beta1 "k8s.io/client-go/kubernetes/typed/admissionregistration/v1beta1"
	// appsv1 "k8s.io/client-go/kubernetes/typed/apps/v1"
	// appsv1beta1 "k8s.io/client-go/kubernetes/typed/apps/v1beta1"
	// appsv1beta2 "k8s.io/client-go/kubernetes/typed/apps/v1beta2"
	// auditregistrationv1alpha1 "k8s.io/client-go/kubernetes/typed/auditregistration/v1alpha1"
	// authenticationv1 "k8s.io/client-go/kubernetes/typed/authentication/v1"
	// authenticationv1beta1 "k8s.io/client-go/kubernetes/typed/authentication/v1beta1"
	// authorizationv1 "k8s.io/client-go/kubernetes/typed/authorization/v1"
	// authorizationv1beta1 "k8s.io/client-go/kubernetes/typed/authorization/v1beta1"
	// autoscalingv1 "k8s.io/client-go/kubernetes/typed/autoscaling/v1"
	// autoscalingv2beta1 "k8s.io/client-go/kubernetes/typed/autoscaling/v2beta1"
	// autoscalingv2beta2 "k8s.io/client-go/kubernetes/typed/autoscaling/v2beta2"
	// batchv1 "k8s.io/client-go/kubernetes/typed/batch/v1"
	// batchv1beta1 "k8s.io/client-go/kubernetes/typed/batch/v1beta1"
	// batchv2alpha1 "k8s.io/client-go/kubernetes/typed/batch/v2alpha1"
	// certificatesv1beta1 "k8s.io/client-go/kubernetes/typed/certificates/v1beta1"
	// coordinationv1 "k8s.io/client-go/kubernetes/typed/coordination/v1"
	// coordinationv1beta1 "k8s.io/client-go/kubernetes/typed/coordination/v1beta1"
	corev1 "k8s.io/client-go/kubernetes/typed/core/v1"
	// discoveryv1alpha1 "k8s.io/client-go/kubernetes/typed/discovery/v1alpha1"
	// discoveryv1beta1 "k8s.io/client-go/kubernetes/typed/discovery/v1beta1"
	// eventsv1beta1 "k8s.io/client-go/kubernetes/typed/events/v1beta1"
	// extensionsv1beta1 "k8s.io/client-go/kubernetes/typed/extensions/v1beta1"
	// flowcontrolv1alpha1 "k8s.io/client-go/kubernetes/typed/flowcontrol/v1alpha1"
	// networkingv1 "k8s.io/client-go/kubernetes/typed/networking/v1"
	// networkingv1beta1 "k8s.io/client-go/kubernetes/typed/networking/v1beta1"
	// nodev1alpha1 "k8s.io/client-go/kubernetes/typed/node/v1alpha1"
	// nodev1beta1 "k8s.io/client-go/kubernetes/typed/node/v1beta1"
	// policyv1beta1 "k8s.io/client-go/kubernetes/typed/policy/v1beta1"
	// rbacv1 "k8s.io/client-go/kubernetes/typed/rbac/v1"
	// rbacv1alpha1 "k8s.io/client-go/kubernetes/typed/rbac/v1alpha1"
	// rbacv1beta1 "k8s.io/client-go/kubernetes/typed/rbac/v1beta1"
	// schedulingv1 "k8s.io/client-go/kubernetes/typed/scheduling/v1"
	// schedulingv1alpha1 "k8s.io/client-go/kubernetes/typed/scheduling/v1alpha1"
	// schedulingv1beta1 "k8s.io/client-go/kubernetes/typed/scheduling/v1beta1"
	// settingsv1alpha1 "k8s.io/client-go/kubernetes/typed/settings/v1alpha1"
	// storagev1 "k8s.io/client-go/kubernetes/typed/storage/v1"
	// storagev1alpha1 "k8s.io/client-go/kubernetes/typed/storage/v1alpha1"
	// storagev1beta1 "k8s.io/client-go/kubernetes/typed/storage/v1beta1"
	vmv1beta1 "github.com/sputnik-systems/alertmanager_bot/pkg/kubernetes/typed/operator.victoriametrics.com/v1beta1"

	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)

type Interface interface {
	CoreV1() corev1.CoreV1Interface
	VMV1Beta1() vmv1beta1.VMV1Beta1Interface
}

// Clientset contains the clients for groups. Each group has exactly one
// version included in a Clientset.
type Clientset struct {
	coreV1    *corev1.CoreV1Client
	vmV1beta1 *vmv1beta1.VMV1Beta1Client
}

// CoreV1 retrieves the CoreV1Client
func (c *Clientset) CoreV1() corev1.CoreV1Interface {
	return c.coreV1
}

// CoreV1 retrieves the CoreV1Client
func (c *Clientset) VMV1Beta1() vmv1beta1.VMV1Beta1Interface {
	return c.vmV1beta1
}

// NewForConfig creates a new Clientset for the given config.
// If config's RateLimiter is not set and QPS and Burst are acceptable,
// NewForConfig will generate a rate-limiter in configShallowCopy.
func NewForConfig(c *rest.Config) (*Clientset, error) {
	configShallowCopy := *c
	if configShallowCopy.RateLimiter == nil && configShallowCopy.QPS > 0 {
		if configShallowCopy.Burst <= 0 {
			return nil, fmt.Errorf("burst is required to be greater than 0 when RateLimiter is not set and QPS is set to greater than 0")
		}
		configShallowCopy.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(configShallowCopy.QPS, configShallowCopy.Burst)
	}
	var cs Clientset
	var err error
	cs.coreV1, err = corev1.NewForConfig(&configShallowCopy)
	cs.vmV1beta1, err = vmv1beta1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	return &cs, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Clientset {
	var cs Clientset
	cs.coreV1 = corev1.NewForConfigOrDie(c)
	cs.vmV1beta1 = vmv1beta1.NewForConfigOrDie(c)

	return &cs
}

// New creates a new Clientset for the given RESTClient.
func New(c rest.Interface) *Clientset {
	var cs Clientset
	cs.coreV1 = corev1.New(c)
	cs.vmV1beta1 = vmv1beta1.New(c)

	return &cs
}
