apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alertmanager-bot.fullname" . }}-templates
  labels:
    {{- include "alertmanager-bot.labels" . | nindent 4 }}
data:
  {{- with .Values.templates }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
