apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alertmanager-bot.fullname" . }}
  labels:
    {{- include "alertmanager-bot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:         
    type: Recreate
  selector:
    matchLabels:
      {{- include "alertmanager-bot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "alertmanager-bot.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "alertmanager-bot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "alertmanager-bot.image.name" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - bot
            - --alertmanager.dest-secret-name=vmalertmanager-{{ include "alertmanager-bot.fullname" . }}
            - --alertmanager.manual-secret-name=vmalertmanager-{{ include "alertmanager-bot.fullname" . }}-manual
            - --alertmanager.url={{ include "alertmanager-bot.alertmanagerURL" . }}
            - --bot.webhook-url={{ include "alertmanager-bot.webhookURL" . }}
            {{- if .Values.bot.publicURL }}
            - --bot.public-url={{ .Values.bot.publicURL }}
            {{- end }}
            - --bot.token=$(BOT_TOKEN)
            - --kube.namespace=$(NAMESPACE)
            {{- if .Values.oidc.enabled }}
            - --oidc.issuer-url=$(OIDC_ISSUER_URL)
            - --oidc.client-id=$(OIDC_CLIENT_ID)
            - --oidc.client-secret=$(OIDC_CLIENT_SECRET)
            {{- end }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "alertmanager-bot.fullname" . }}
                  key: bot_token
            {{- if .Values.oidc.enabled }}
            - name: OIDC_ISSUER_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "alertmanager-bot.fullname" . }}
                  key: oidc_issuer_url
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "alertmanager-bot.fullname" . }}
                  key: oidc_client_id
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "alertmanager-bot.fullname" . }}
                  key: oidc_client_secret
            {{- end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
