{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "alertmanager-bot.fullname" . }}
  labels:
    {{- include "alertmanager-bot.labels" . | nindent 4 }}
rules:
- apiGroups:
  - operator.victoriametrics.com
  resources:
  - vmrules
  verbs:
  - get
  - list
  # - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  # - list
  # - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  # - create
  # - delete
  # - deletecollection
  - patch
  - update
{{- end }}
