apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmanager-bot.fullname" . }}
  labels:
    {{- include "alertmanager-bot.labels" . | nindent 4 }}
data:
  bot_token: {{ .Values.bot.token | b64enc | quote }}
  alertmanager.yaml: {{ .Values.alertmanager.configOverride | b64enc | quote }}
