apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmanager-bot.fullname" . }}
  labels:
    {{- include "alertmanager-bot.labels" . | nindent 4 }}
data:
  bot_token: {{ .Values.bot.token | b64enc | quote }}
  {{- if .Values.oidc.enabled }}
  oidc_issuer_url: {{ .Values.oidc.issuerURL | b64enc | quote }}
  oidc_client_id: {{ .Values.oidc.clientID | b64enc | quote }}
  oidc_client_secret: {{ .Values.oidc.clientSecret | b64enc | quote }}
  {{- end }}
