apiVersion: v1
kind: Secret
metadata:
  name: vmalertmanager-{{ include "alertmanager-bot.fullname" . }}-manual
  labels:
    {{- include "alertmanager-bot.labels" . | nindent 4 }}
data:
  alertmanager.yaml: {{ .Values.alertmanager.config | b64enc | quote }}
