apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: {{ include "alertmanager-bot.fullname" . }}
  labels:
    {{- include "alertmanager-bot.labels" . | nindent 4 }}
spec:
  replicaCount: 1

  image:
    tag: {{ .Values.vmalert.tag }}

  datasource:
    url: {{ default "http://vmsingle-default:8429" .Values.vmsingle }}

  notifier:
    url: http://vmalertmanager-{{ include "alertmanager-bot.fullname" . }}:9093

  extraArgs:
    {{- toYaml .Values.vmalert.extraArgs | nindent 4 }}
