apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": pre-install
  name: vmalertmanager-{{ include "alertmanager-bot.fullname" . }}
  labels:
    {{- include "alertmanager-bot.labels" . | nindent 4 }}
data:
  alertmanager.yaml: {{ .Values.alertmanager.config | b64enc | quote }}
