apiVersion: v1
stringData:
  alertmanager.yml: |+
    global:
      resolve_timeout: 5m
    
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: empty
    
    receivers:
      - name: empty
      # - name: "-592919675"

    inhibit_rules:
      - source_match:
          severity: 'warning'
        target_match:
          severity: 'info'
        equal: ['alertname', 'instance']
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'instance']
kind: Secret
metadata:
  name: vmalertmanager-test
type: Opaque
